### ISSUE TITLE
Bring back the concept of epo:Channel

### ISSUE THREAD

**Issue by costezki** [eprocurementontology/eprocurementontology#435]
In the eOOrdering WGM it became clear that a more complex communication channel shall be expressed for a Buyer/Seller Role. 
Therefore the `epo:Channel` class needs to be re-created (as it is in EPO v3.1.0). 
Also the URLs that moved to `epo:AccessTerm` may have to be brought back into the `epo:Channel` Class. 

![image](https://user-images.githubusercontent.com/13567133/218786289-04f68f7e-e45d-4fba-ab4b-4f2e3f9f180a.png)
![image](https://user-images.githubusercontent.com/13567133/218786425-8d81ff21-af5c-445a-8271-a603fbe0c688.png)

**Comment by andreea-pasare** [comment]
Channel & AccessTerm has been discussed in the last WGM and the implementation is depicted in the diagrams above:
![image](https://user-images.githubusercontent.com/88081600/220663167-a77d22f2-aab8-4700-9138-cfaad4cc67e5.png)

The attribute epo:hasToolsACcessURL has been removed from AccessTerm concept:
![image](https://user-images.githubusercontent.com/88081600/220663899-6c6ff496-b6b1-435a-ac9b-026fb0134a62.png)

We will use instead the relation from the first diagram: epo:exposesAdhocTools.

We also checked that it covers both standard forms and eForms.
